### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by familqasimov** [bashu/django-fineuploader#8]
Hi sir. I have studied your work and I think a new logo will make you more visible. I would like to offer you logo. I can give you all the formats of the design free. If you want a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/39088770-39b76e48-45c9-11e8-8f0e-d225b5c7157d.png)

**Comment by bashu** [comment]
@familqasimov show me sources open and send PR @cybersimon which one you like the most?

**Comment by bashu** [comment]
@familqasimov can you post sources?

**Comment by familqasimov** [comment]
Hi friend. I have got some works. I sent today. Say me please, which color
you selected?

24 apr 2018, Ç.A. 06:11 tarixində Basil Shubin <notifications@github.com>
yazdı:

**Comment by cybersimon** [comment]
@bashu 
I like the bottom right one the best (white on black). If you're going with a color one I'd choose the green 😃

**Comment by familqasimov** [comment]
Hi friend. Please all files hire https://drive.google.com/drive/folders/1NHlIaJMQo4l8voHQigoU4thoAcdxEFoB

**Comment by familqasimov** [comment]
Hi sir. I sent you PR. I tried it but the logo did not appear in the
Readme.md file. Believe me, after this project, I worked on three projects
and accepted by project owners. If possible, please. You would help me see
the logo in the Readme.md file.

26 apr 2018, C.A. 10:16 tarixində cybersimon <notifications@github.com>
yazdı:
